# Copyright (c) 1996 James Clark, 1999 Matthias Clasen
# See the file COPYING for copying permission

=2000

I2+versionInfo++%1 version %2
E0+noSpec++no DSSSL specification: use -d to specify
E2+noSpecTitle++no applicable processing instruction with title %1; available titles: %2
I1+prefixInfo++Options with a "doc-"/"spec-" prefix apply only to the document/specification.
I1+help2++Enable experimental DSSSL extensions.
I1+GHelp++Debug mode.
I1+dHelp++Use DSSSL specification %1.
I1+THelp++Use DSSSL specification with title %1.
I1+VHelp++Pretend that %1 appeared in the specification.
I1+sHelp++Strict DSSSL compliance mode.
I1+eHelp++Show open entities in error messages.
I1+gHelp++Show open elements in error messages.
I1+nHelp++Show error numbers in error messages.
I1+xHelp++Show references in error messages.
I1+iHelp++Define parameter entity %1 as "INCLUDE".
I1+wHelp++Enable warning %1.
+sysid++SYSID
+vardef++DEFINITION
+name++NAME
+type++TYPE
