!cxx
E0+unexpectedEof++unexpected end of file
E0+invalidChar++invalid character
E0+unknownHash+ISO/IEC 10179:1996 8.5.1 8.5.6 8.5.7.4 8.5.8 12.5.5 [70] [76] [79] [80] [81] [82] [94] [187]+invalid character after '#'
E1+unknownNamedConstant+ISO/IEC 10179:1996 8.5.6 [76]+unknown #! named constant %1
E1+unexpectedToken++unexpected token %1
E0+unterminatedString+ISO/IEC 10179:1996 8.5.9 [118]+string with no closing quote
E0+missingCloseParen++missing closing parenthesis
E1+invalidNumber+ISO/IEC 10179:1996 8.5.7.4+invalid number %1
E1+invalidAfiiGlyphId+ISO/IEC 10179:1996 12.5.5+invalid AFII glyph identifier %1
E1+callNonFunction+ISO/IEC 10179:1996 8.3.1.3+call of non-function object %1
E0+tooManyArgs+ISO/IEC 10179:1996 8.3.1.4+too many arguments for function
E0+oddKeyArgs+ISO/IEC 10179:1996 8.3.1.4+odd number of keyword/value arguments
E0+missingArg+ISO/IEC 10179:1996 8.3.1.4+missing argument for function call
E1+syntacticKeywordAsVariable+ISO/IEC 10179:1996 8.2.1p1+syntactic keyword %1 used as variable
E1+undefinedVariableReference+ISO/IEC 10179:1996 8.3.1.1+reference to undefined variable %1
E1+badCharName+ISO/IEC 10179:1996 8.5.8+no character with name %1
-E1+keywordNotAllowedCall++syntactic keyword %1 not valid in call position
-E1+symbolRequired++symbol required (got %1)
E1+unknownTopLevelForm+ISO/IEC 10179:1996 12 [159]+unknown top level form %1
E1+badModeForm+ISO/IEC 10179:1996 12.4.1 [162]+bad form %1 in mode group
E1+duplicateDefinition+ISO/IEC 10179:1996 8.4+identifier %1 already defined in same part+first definition was here
E1+identifierLoop+ISO/IEC 10179:1996 8.4+loop in specification of value of %1
E0+outOfRange+ISO/IEC 10179:1996 8.5.3.12 8.5.3.13 8.5.7.17 8.5.7.19 8.5.7.20 8.5.9.4 8.5.9.7+argument out of range
E1+unitLoop+ISO/IEC 10179:1996 8.4+loop in specification of value of unit %1
E1+badUnitDefinition+ISO/IEC 10179:1996 8.5.7.1+bad value specified for unit %1
E1+duplicateUnitDefinition+ISO/IEC 10179:1996 8.4+unit %1 already defined in same part+first definition was here
E1+undefinedQuantity++quantity %1 undefined
E0+incompatibleDimensions+ISO/IEC 10179:1996 8.5.7.7 8.5.7.9 8.5.7.10 8.5.7.12 8.5.7.19+incompatible dimensions
E3+notABoolean++%2 argument for primitive %1 of wrong type: %3 not a boolean
E3+notAPair++%2 argument for primitive %1 of wrong type: %3 not a pair
E3+notAList++%2 argument for primitive %1 of wrong type: %3 not a list
E3+notASymbol++%2 argument for primitive %1 of wrong type: %3 not a symbol
E3+notAString++%2 argument for primitive %1 of wrong type: %3 not a string
E3+notAStringOrSymbol++%2 argument for primitive %1 of wrong type: %3 not a string or symbol
E3+notAChar++%2 argument for primitive %1 of wrong type: %3 not a char
E3+notATimeString++%2 argument for primitive %1 of wrong type: %3 not an ISO8601 time string
E3+notAStyle++%2 argument for primitive %1 of wrong type: %3 not a style
E3+notAnExactInteger++%2 argument for primitive %1 of wrong type: %3 not an exact integer
E3+notAQuantity++%2 argument for primitive %1 of wrong type: %3 not a quantity
E3+notAColorSpace++%2 argument for primitive %1 of wrong type: %3 not a color-space
E3+notANumber++%2 argument for primitive %1 of wrong type: %3 not a number
E3+notASosofo++%2 argument for primitive %1 of wrong type: %3 not a sosofo
E3+notAnOptSingletonNode++%2 argument for primitive %1 of wrong type: %3 not an optional singleton node list
E3+notASingletonNode++%2 argument for primitive %1 of wrong type: %3 not a singleton node list
E3+notANodeList++%2 argument for primitive %1 of wrong type: %3 not a node list
E3+notANamedNodeList++%2 argument for primitive %1 of wrong type: %3 not a named node list
E3+notALengthSpec++%2 argument for primitive %1 of wrong type: %3 not a length or length-spec
E3+notAQuantityOrLengthSpec++%2 argument for primitive %1 of wrong type: %3 not a quantity or length-spec
E3+notAPriority+ISO/IEC 10179:1996 12.5.4.1+%2 argument for primitive %1 of wrong type: %3 not an integer or the symbol "force"
-E3+notAPattern++%2 argument for primitive %1 of wrong type: %3 not a valid element matching pattern
E3+notAnAddress+ISO/IEC 10179:1996 12.5.8+%2 argument for primitive %1 of wrong type: %3 not an address
E3+notAGlyphId+ISO/IEC 10179:1996 12.5.5+%2 argument for primitive %1 of wrong type: %3 not a glyph-id
E3+notAGlyphSubstTable+ISO/IEC 10179:1996 12.5.6+%2 argument for primitive %1 of wrong type: %3 not a glyph-subst-table
E3+notAGlyphIdPairList+ISO/IEC 10179:1996 12.5.6+%2 argument for primitive %1 of wrong type: %3 not a list of pairs of glyph-ids
E3+notAProcedure++%2 argument for primitive %1 of wrong type: %3 not a procedure
E3+notAVector++%2 argument for primitive %1 of wrong type: %3 not a vector
E0+duplicateRootRule+ISO/IEC 10179:1996 12.4.1+root rule already defined in same part with same importance+first definition was here
E1+duplicateInitialValue+ISO/IEC 10179:1996 12.4.6+initial value already declared for characteristic %1 in same part+first declaration was here
E1+invalidStyleKeyword+ISO/IEC 10179:1996 12.4.5+%1 is not a valid keyword in a style expression
E2+invalidMakeKeyword+ISO/IEC 10179:1996 12.4.3+%1 is not a valid keyword in a make expression for flow object class %2
E1+unknownFlowObjectClass++%1 is not the name of any flow object class
E1+atomicContent+ISO/IEC 10179:1996 12.4.3+content expression cannot be specified in make expression for atomic flow object class %1
E0+labelNotASymbol+ISO/IEC 10179:1996 12.4.3+value for "label:" not a symbol
E1+badConnection++no port for label %1
E0+badContentMap+ISO/IEC 10179:1996 12.4.3+invalid content map
E1+contentMapBadPort+ISO/IEC 10179:1996 12.4.3+content map references non-existent port %1
E1+invalidCharacteristicValue++invalid value for %1 characteristic
E0+condFail+ISO/IEC 10179:1996 8.3.2.1+no clause in cond expression matched
E1+caseFail+ISO/IEC 10179:1996 8.3.2.2+no clause in case expression matched %1
E1+caseElse+ISO/IEC 10179:1996 8.3.2.2 [45]+expected "else" not %1
E0+caseUnresolvedQuantities++sorry, cannot handle unresolvable quantities in datums in case expression
E1+errorProc+ISO/IEC 10179:1996 8.5.12+%1
E0+divideBy0+ISO/IEC 10179:1996 8.5.7.13+division by zero
E1+invalidKeyArg+ISO/IEC 10179:1996 8.3.1.4+procedure does not have %1 keyword argument
E0+keyArgsNotKey+ISO/IEC 10179:1996 8.3.1.4+argument not a keyword
-E0+oneBody++support for more than one style-specification-body not yet implemented
E0+specNotArc+ISO/IEC 10179:1996 7p1+specification document does not have the DSSSL architecture as a base architecture
E0+noStyleSpec+ISO/IEC 10179:1996 7.1+specification document did not contain a style-specification-body element
E1+unknownCharName+ISO/IEC 10179:1996 8.5.8+unknown character name %1
E0+noCurrentNode+ISO/IEC 10179:1996 10.1.1 12.4.1+attempt to use current node when there is none
E0+noCurrentProcessingMode+ISO/IEC 10179:1996 12.4.1+attempt to process node in illegal context
E0+invalidRadix++radix must be 2, 8, 10 or 16
E0+sosofoContext++this context requires a sosofo
E0+styleContext++this context requires a style object
E0+notInCharacteristicValue+ISO/IEC 10179:1996 12.4.6+procedure can only be used in evaluation of characteristic value
-E1+expressionNotImplemented++sorry, %1 expression not implemented
E1+colorArgCount++%1 color requires three arguments
E1+colorArgType++arguments for %1 color must be numbers
E1+colorArgRange++arguments for %1 color must be in the range 0 to 1
E1+colorProcResType++result of procedure in %1 color must be a number
E1+unknownColorSpaceFamily+ISO/IEC 10179:1996 12.5.9+unknown color-space family %1
E1+colorSpaceNoArgs++%1 color-space family does not take any arguments
E1+colorSpaceArgError++invalid parameters for %1 color-space family
E1+notABuiltinInheritedC++%1 is not a pre-defined inherited characteristic
E1+invalidNumberFormat+ISO/IEC 10179:1996 8.5.7.24+invalid number format %1
E1+invalidPublicIdChar++invalid character %1 in public identifier
I1+debug++debug %1
E0+useLoop+ISO/IEC 10179:1996 7.1+circular use of specification parts
E1+missingPart+ISO/IEC 10179:1996 7.1+no style-specification or external-specification with ID %1
E0+noParts+ISO/IEC 10179:1996 7.1+document did not contain any style-specifications or external-specifications
E0+tableCellOutsideTable++table-cell flow object not inside a table
E0+tableRowOutsideTable++table-row flow object not inside a table
E1+noNodePropertyValue+ISO/IEC 10179:1996 10.1.6+no value for node property %1
E0+returnNotNodeList++value returned by procedure was not a node-list
I0+stackTrace++called from here
I1+stackTraceEllipsis++called from here...(%1 calls omitted)
E0+processNodeLoop++node processing loop detected
E0+spliceNotList+ISO/IEC 10179:1996 8.3.2.7+unquote-splicing expression does not evaluate to a list
E0+readOnly++object is read-only
E1+topLevelAssignment++assignment to top-level variable %1
E0+continuationDead++invalid call to continuation
E0+patternEmptyGi++empty generic identifier in pattern
E0+patternNotList++pattern is not a list
E1+patternBadGi++%1 cannot be used as a generic identifier in a pattern
E1+patternBadMember++%1 cannot occur in a pattern
E0+patternMissingQualifierValue++value missing for qualifier in pattern
E1+patternUnknownQualifier++unknown pattern qualifier %1
E2+patternBadQualifierValue++bad value %1 for %2 qualifier in pattern
E0+patternChildRepeat++repeat qualifier not allowed inside children qualifier
E0+patternBadAttributeQualifier++bad value for attributes qualifier in pattern
E1+ambiguousStyle++characteristic %1 applied in style rule with same specificity+other style rule is here
E0+ambiguousMatch+ISO/IEC 10179:1996 12.4.1+node matches more than one pattern with the same specificity
E1+uninitializedVariableReference++reference to uninitialized variable %1
E1+actualLoop+ISO/IEC 10179:1996 12.4.6+circular use of actual value of characteristic %1
E1+duplicateCharacteristic+ISO/IEC 10179:1996 12.4.6+characteristic %1 already defined in same part+first definition was here
E1+duplicateFlowObjectClass+ISO/IEC 10179:1996 12.4.3 [178]+flow object class %1 already defined in same part+first definition was here
E1+undefinedMode+ISO/IEC 10179:1996 12.4.3 [180]+mode %1 not defined
E1+duplicateCharName+ISO/IEC 10179:1996 7.1.4+duplicate character name %1
E1+duplicateSdataEntityName+ISO/IEC 10179:1996 7.1.8+duplicate SDATA entity name %1
E1+duplicateSdataEntityText+ISO/IEC 10179:1996 7.1.8+duplicate SDATA entity text %1
W0+unsupportedDeclaration++unsupported declaration will be ignored
W1+unsupportedCharRepertoire++unsupported character repertoire %1 will be ignored
E0+badDeclaration++error in declaration element
-E1+duplicateDeclaration++duplicate declaration element (%1)
E1+invalidIdentifier+ISO/IEC 10179:1996 7.3.2 [1]+%1 is not a valid identifier
E0+badLanguageDefinition+ISO/IEC 10179:1996 8.5.8.2.1 [100]+error in language definition
E0+noCurrentLanguage+ISO/IEC 10179:1996 8.5.8.4 8.5.8.5 8.5.8.6 8.5.9.5 8.5.9.6+no current language
E3+notALanguage+ISO/IEC 10179:1996 8.5.8.2+%2 argument for primitive %1 of wrong type: %3 not a language
E3+notAPositiveInteger++%2 argument for primitive %1 of wrong type: %3 not a positive integer
E3+notAnInteger++%2 argument for primitive %1 of wrong type: %3 not an integer
E3+notAKeyword++%2 argument for primitive %1 of wrong type: %3 not a keyword
E3+notAnAlist++%2 argument for primitive %1 of wrong type: %3 not an alist
E3+notACharList++%2 argument for primitive %1 of wrong type: %3 not a list of characters
E3+lengthError++%2 argument for primitive %1 has wrong length
W1+noExactRepresentation+ISO/IEC 10179:1996 8.5.7.2+quantity %1 can't be represented exactly
E0+duplicateDefLangDecl+ISO/IEC 10179:1996 8.5.8.2 [99]+default language already declared in this part+first declaration was here
E1+defLangDeclRequiresLanguage+ISO/IEC 10179:1996 8.5.8.2+%1 not a language as required in a default-language-declaration
E1+invalidUnitName+ISO/IEC 10179:1996 8.5.7.4 [87]+%1 not a valid unit name
E1+invalidCharName+ISO/IEC 10179:1996 8.5.8 [95]+%1 not a valid character name
E1+invalidCharNumber+ISO/IEC 10179:1996 7.1.4p2 7.1.6p2+%1 not a valid character number
E1+unknownCharProperty+ISO/IEC 10179:1996 8.5.8.1+unknown character property %1
E0+badAddCharProperty+ISO/IEC 10179:1996 8.5.8.1+error in character property declaration
E1+duplicateCharPropertyDecl+ISO/IEC 10179:1996 8.5.8.1+character property %1 already declared in same part+first declaration was here
# FIXME: Would like to report both property name and character, but there is
# no MessageType2L in Message.h.
E1+duplicateAddCharProperty+ISO/IEC 10179:1996 8.5.8.1+added value for character property %1 already declared in same part+previous declaration was here
E0+returnNotSosofo++value returned by procedure was not a sosofo
E1+charPropertyLoop++loop in specification of value of character property %1
E2+charPropertyNotInteger++value for character property %1 of wrong type: %2 not an integer
E2+charPropertyNotIntegerOrFalse++value for character property %1 of wrong type: %2 not an integer or the value "#f"
E1+unknownFeature+ISO/IEC 10179:1996 11.1 12.1+%1 not a style or transformation language feature
E1+missingFeature+ISO/IEC 10179:1996 7.1.1+undeclared use of feature %1
W1+unsupportedFeature++feature %1 not supported
W1+partiallySupportedFeature++feature %1 only partially supported
E0+styleLanguage++only allowed in style language
E0+transformationLanguage++only allowed in transformation language
E0+mixedLanguages+ISO/IEC 10179:1996 7.1+style and transformation language parts mixed
W0+partialSpec+ISO/IEC 10179:1996 7.1+specification is marked as partial
W1+cantOmitModule++grove plan excluding module %1 not supported
W1+cantAddModule++grove plan including module %1 not supported
E1+unknownModule++%1 not an SGML property set module
E2+notACharInCharMap+ISO/IEC 10179:1996 12.6.11+Function for char-map characteristic returned non-char object %2 for character %1
E2+charPropertyNotPublicId++value for character property %1 of wrong type: %2 not a public identifier or the value "#f"
E1+duplicateVariableBinding+ISO/IEC 10179:1996 8.3.2.5+variable %1 occurs more than once in bindings
E0+subgroveArgs+ISO/IEC 10179:1996 11.3.1+exactly one of node:, subgrove: and class: needed
W0+subgroveSubgroveArgs+ISO/IEC 10179:1996 11.3.1+add:, null:, remove:, children:, sub: make no sense with subgrove:
W0+subgroveClassArgs+ISO/IEC 10179:1996 11.3.1+remove: makes no sense with class:
E3+notASubgroveSpec++%2 argument for primitive %1 of wrong type: %3 not a subgrove-spec
E1+notACspecList++wrong type: %1 not a list of create-specs
E1+notACspecOrCspecList++wrong type: %1 not a create-spec or list of create-specs
E1+queryNotANodeList+ISO/IEC 10179:1996 11.2 12.4.1 [152] [164]+query expression: %1 not a node list
E1+priorityNotAnExactInteger+ISO/IEC 10179:1996 11.2 12.4.1 [152] [164]+priority expression: %1 not an exact integer
E0+badTopLevelFlowObj+ISO/IEC 10179:1996 12.4.1+flow objects at the root must be all of class scroll or all of class page-sequence or simple-page-sequence
E0+noPrincipalPort++current flow parent has no principal port
E0+noParagraphAncestor++this flow object requires a paragraph as an ancestor flow object
E0+notInlineFlowObj++flow object not accepted by port; only inline flow objects accepted
E0+notDisplayFlowObj++flow object not accepted by port; only display flow objects accepted
E0+notInlineOrDisplayFlowObj++flow object not accepted by port; only display or inline flow objects accepted
E0+notValidInParagraph++flow object not accepted in a paragraph; only inline, display or paragraph-break flow objects accepted
E0+notSideBySideItem++a side-by-side flow object only accepts side-by-side-item flow objects as children
E0+notMathSequence++flow object not accepted by port; only math-sequence, unmath, subscript, superscript, script, mark, fence, fraction, radical, math-operator, grid, character and alignment-point flow objects accepted
E0+notGridCell++flow object not accepted by port; must be grid-cell
E0+notSingleChar++flow object not accepted by port; only a single character flow object accepted
E0+badTableContent++flow object not accepted by port; in a table, only either table-part flow objects or table-column flow objects followed by table-row or table-cell flow objects are allowed
E0+badTablePartHF++flow object not accepted by port; only table-row or table-cell flow objects accepted
E0+badTablePartBody++flow object not accepted by port; only table-column flow objects followed by table-row or table-cell flow objects allowd
E0+badTableRow++flow object not accepted by port; only table-cell flow objects accepted
E0+priorityNotNumber++priority-expression must be a number
E0+queryNotNodelist++query-expression must be a node-list
E0+sorryPriority++Sorry, non-integral priorities not implemented
